version: '3'
services:
  python-server:
    build: . 
    image: python-server
    container_name: python-server
    ports:
      - "5000:5000"  
    volumes:
      - ./templates:/app/templates  
    restart: always  
